### ISSUE TITLE
已经能被杀了

### ISSUE THREAD

**Issue by SmallFang2009** [ZackSecurity/Phobos#6]
![image](https://github.com/ZackSecurity/Phobos/assets/129593198/71f67557-aa82-4cbf-909e-ede3e539eb80)

**Comment by ZackSecurity** [comment]
> ![image](https://user-images.githubusercontent.com/129593198/261853316-71f67557-aa82-4cbf-909e-ede3e539eb80.png)

项目已经开源，请自行修改源码达到免杀效果

**Comment by SmallFang2009** [comment]
![001740C2](https://github.com/ZackSecurity/Phobos/assets/129593198/e98450bd-8223-4831-a63a-905f4ee1be2b)
